#!/usr/bin/env bash

# install: installs dotfiles
#
# ./install pkgs..
# set -x
set -e

script_dir="$(dirname "$0")"

# ensure gnu stow is installed
if ! command -v stow >/dev/null 2>&1; then
	echo "GNU stow is not installed, attempting to install it:"
	if [[ "$(uname -s)" == "Darwin" ]] && command -v brew >/dev/null 2>&1; then
		echo "-- attempting to install using brew"
		brew install stow
	elif command -v apt >/dev/null 2>&1; then
		echo "-- attempting to install using sudo apt install"
		sudo apt install stow
	else
		echo "FATAL: could not find gnu stow, or any way to install it."
		exit 2
	fi

	echo "-- done"
fi

# --no-folding
# Only symlink files, not directories.
#
# Without this flag, when trying to stow a file in a directory that does not 
# exist, stow will symlink the entire directory. Creating additional files in 
# that directory will make them appear in .dotfiles as well, which is not what 
# I want.
#
# https://news.ycombinator.com/item?id=7927930

stow -R \
	--target "$HOME" \
	--dir "$script_dir" \
  --no-folding \
	"$@"

echo "Stowed: $*"
echo "Running post-install scripts:"
for pkg in "$@"; do
	if [[ -x "$script_dir/$pkg/setup" ]]; then
		echo "-- running setup script for $pkg"
    "./$script_dir/$pkg/setup"
	else
		echo "-- skipping setup for $pkg: $script_dir/$pkg/setup does not exist or is not executable."
	fi
done
