#!/usr/bin/env bash

# install: installs dotfiles
#
# ./install pkgs..
#
# ./install --skip-setup pkgs
#
# The second form symlinks the given packages but skips the setup scripts.
#
# set -x
set -e

script_dir="$(dirname "$0")"
skip_setup=false

if [[ "$1" == "--skip-setup" ]]; then
	skip_setup=true
	shift 1
fi

if command -v stow >/dev/null 2>&1; then
  echo "found GNU stow"
  stow="GNU"
elif command -v xstow > /dev/null 2>&1; then
  echo "found xstow"
  stow="xstow"
else
  echo "FATAL: cannot find xstow or gnu stow!"
  exit 1
fi


if [[ $stow == "GNU" ]]; then
  # --no-folding
  # Only symlink files, not directories.
  #
  # Without this flag, when trying to stow a file in a directory that does not
  # exist, stow will symlink the entire directory. Creating additional files in
  # that directory will make them appear in .dotfiles as well, which is not what
  # I want.
  #
  # https://news.ycombinator.com/item?id=7927930

  stow -R \
    --target "$HOME" \
    --dir "$script_dir" \
    --no-folding \
    --ignore='^setup$' \
    --ignore='^README\.md$' \
    --ignore='.DS_Store' \
    "$@"
elif [[ $stow == "xstow"  ]]; then
  xstow -R \
    -target "$HOME" \
    -dir "$script_dir" \
    -ire '(^setup$|^README\.md$|.DS_Store|.stow-local-ignore)' \
    "$@"
else
  exit 1
fi

echo "Stowed: $*"

if [ "$skip_setup" = true ] ; then
  echo "Skipping post-install setup scripts."
	exit 0
fi

echo "Running post-install setup scripts:"
for pkg in "$@"; do
	if [[ -x "$script_dir/$pkg/setup" ]]; then
		echo "-- running setup script for $pkg"
		"./$script_dir/$pkg/setup"
	else
		echo "-- skipping setup for $pkg: $script_dir/$pkg/setup does not exist or is not executable."
	fi
done
