#!/bin/bash
mkdir -p ~/cs/home
mkdir -p ~/cs/studres

# Unmount first
fusermount -u ~/cs/home
fusermount -u ~/cs/studres

# Mount using rclone

rclone mount --daemon cs-home:/cs/home ~/cs/home
rclone mount --daemon cs-home:/cs/studres ~/cs/studres
