# do not edit this file, edit .profile or .bashrc instead

# see https://superuser.com/a/789465

if [ -e "$HOME/.profile" ]; then
	. "$HOME/.profile"
fi

# a bash login shell that is always interactive (i.e. most of them) will only
# source .bash_profile. We know that bash_profile is bash, so from it we can
# safely source bashrc.
if [ -e "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
fi
